# Copyright 2017, Backblaze Inc. All Rights Reserved.
# License https://www.backblaze.com/using_b2_code.html

# travis-ci is about to change the default to 'trusty', so let's
# switch to it on purpose.  we can probably remove in August 2017.
# see https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

os: linux
dist: trusty 
language: java
jdk:
  - oraclejdk8
env:
  global:
    - OUTPUT_DIR=build/outputs
    - OUTPUT_ZIP=b2-sdk-build-${TRAVIS_BUILD_NUMBER}.zip
    - PYENV_VERSION=3.6

before_install:
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
  - pip3 install b2

script:
  #
  # actually build
  #

  - ./gradlew build javadoc writeNewPom

  #
  # Prepare the outputs
  #

  # make the directory
  - mkdir -p build/outputs
  
  # copy the generated jar files & pom files
  - cp -v */build/libs/b2-sdk-*.{jar,pom} build/outputs

  # find the jar's version.
  - VERSION=$(head -1 core/build/resources/main/b2-sdk-core/version.txt | awk "-F'" '{print $1}')
  - echo VERSION=$VERSION

  # zip up the outputs
  - echo OUTPUT_ZIP=$OUTPUT_ZIP
  - (cd $OUTPUT_DIR; zip -r $TRAVIS_BUILD_DIR/build/$OUTPUT_ZIP *)

  #
  # upload to b2 (if credentials are provided, as they will be for backblaze's builds, but not pull requests)
  # This should be using python 3.4
  # 
  - ./maybe_upload_build_results $OUTPUT_ZIP

  ## list all files to help debug stuff!
  #- find $TRAVIS_BUILD_DIR

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

# note that i'm only uploading the javadocs for b2-sdk-core.
# that's because i'm lame and building separate javadocs for
# each jar and only uploading one set of javadocs.
deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: core/build/docs/javadoc
  on:
    branch: master
